paths:
  data_path: "Data/MIND"
  out_basedir: "src/tmp"
  feature_extractor_path: "./feature_extractor.py"
  user_history_path: "/data2/zhy/Movie_Recsys/Data/MovieLens_1M_data/user_history.json"

features:
  feature_names:
    - user_id
    - item_id
    - category
    - subcategory
    - user_click_category
  
  item_feature_names:
    - item_id
    - category
    - subcategory
  
  array_feature_names: []

  share_emb_table_features: {} # 共享embedding表的特征名称

  array_max_length: {}